Feature/thumbnails
LCOGT/ingester pull request #48
Opened 2024-05-16 23:21 UTC by mgdaily

These are the ingester changes to support ingesting thumbnails to the science archive. The main change is to redirect the thumbnail payload to the /thumbnails endpoint if the file is a type defined in the ocs_archive as a thumbnail type. This relies on some small ocs_archive changes that I'll open a PR for.

The client side looks like this:

```python
    thumbnail_filename = '/Users/mdaily/Documents/ingester/thumbnail_testing/tfn0m419-sq32-20240426-0097-e91-small.jpg'
    fits_filename = '/Users/mdaily/Documents/ingester/thumbnail_testing/tfn0m419-sq32-20240426-0097-e91.fits.fz'
    # get header metadata from the main FITS image
    metadata = dict(fits.getheader(fits_filename, extname='SCI'))
    metadata['frame_basename'] = os.path.basename(fits_filename).split('.')[0]
    metadata['size'] = 'small'

    with open(thumbnail_filename, 'rb') as f:
        record = upload_file_and_ingest_to_archive(f, file_metadata=metadata)
```

2024-05-17 21:11 UTC, jnation3406 requested changes
What do you think about having the caller of the ingester function specify if its a thumbnail and what "size", rather than inferring it?

2024-05-17 21:11 UTC, jnation3406 commented on ocs_ingester/ingester.py
> +def ingest_archive_frame_record(version, record, api_root=ingester_settings.API_ROOT,
This rename probably also affects the shipper and ocs_example as well.

2024-05-17 21:11 UTC, jnation3406 commented on ocs_ingester/ingester.py
> +        # we need to make sure that
this comment seems incomplete

2024-05-17 21:11 UTC, jnation3406 commented on ocs_ingester/ingester.py
> +        return self.archive.post_thumbnail(record) if self.datafile.open_file.extension in archive_settings.THUMBNAIL_FILETYPES else self.archive.post_frame(record)
I'm not sure about this... The archive is supposed to be flexible so imagine you are using the archive to store your raw image files (not fits)... that should work but this new logic can't differentiate between a thumbnail and "full image" that is also a jpeg. I think it might be better to make it explicit when ingesting that this is a small/large/whatever thumbnail when ingesting rather than infer it? I.e. the caller of the ingester should know, so they can decide.

2024-05-17 21:28 UTC, mgdaily commented on ocs_ingester/ingester.py
> +        return self.archive.post_thumbnail(record) if self.datafile.open_file.extension in archive_settings.THUMBNAIL_FILETYPES else self.archive.post_frame(record)
That makes a lot of sense. Let me re-think that. I was trying to minimize client changes, but inference is fragile.

2024-05-17 21:28 UTC, mgdaily commented on ocs_ingester/ingester.py
> +        # we need to make sure that
D'oh. Sorry

2024-05-20 23:12 UTC, jnation3406 approved these changes
Looks good now!

2024-06-03 20:13 UTC, merged